Move get_tor_start_command() to torrc-parser
/usr/lib/anon-gw-anonymizer-config/torrc-parser will serve as a
general library that can be used by many different scriptes. It offers
different function calls that set variables. /usr/bin/anon-verify will
serve as one of those callers.

diff --git a/usr/lib/anon-gw-anonymizer-config/torrc-parser b/usr/lib/anon-gw-anonymizer-config/torrc-parser
--- a/usr/lib/anon-gw-anonymizer-config/torrc-parser
+++ b/usr/lib/anon-gw-anonymizer-config/torrc-parser
@@ -10,6 +10,25 @@ torrc_all_in_one=
 
 declare -a torrc_files
 
+## get_tor_start_command() will set the $tor_start_command to the command
+## used in Whonix to start Tor. If it did not successfully extract the
+## command, it will exit with exit code 1.  If Whonix get rid of
+## systemd for Tor control in the future, we simply change the content
+## in the tor_start_command
+function get_tor_start_command() {
+    ## Tor use systemd to start
+    tor_start_command=$(grep -i "ExecStart=" /lib/systemd/system/tor@default.service | sed s/ExecStart=//g)
+
+    if [ -z "$tor_start_command" ]; then
+        echo "[error] Failed to extra commands used to start Tor." >&2
+        return 1
+    fi
+
+    ## Tor is run as root, we need to simulate this, too.
+    tor_start_command="sudo $tor_start_command"
+}
+
+
 function parser() {
     for abs_path in "$@"; do
 	local abs="$abs_path"
